#[cfg(feature = "plugins")]
pub mod dns_server;
pub mod dyn_outbound;
#[cfg(feature = "plugins")]
pub mod fakeip;
#[cfg(feature = "plugins")]
pub mod fallback;
#[cfg(feature = "plugins")]
pub mod forward;
#[cfg(feature = "plugins")]
pub mod host_resolver;
#[cfg(feature = "plugins")]
pub mod http_proxy;
#[cfg(feature = "plugins")]
pub mod ip_stack;
pub mod netif;
#[cfg(feature = "plugins")]
pub mod null;
#[cfg(feature = "plugins")]
pub mod obfs;
#[cfg(feature = "plugins")]
pub mod redirect;
#[cfg(feature = "plugins")]
pub mod reject;
#[cfg(feature = "plugins")]
pub mod resolve_dest;
pub mod rule_dispatcher;
pub mod shadowsocks;
pub mod simple_dispatcher;
#[cfg(feature = "plugins")]
pub mod socket;
#[cfg(feature = "plugins")]
pub mod socks5;
#[cfg(feature = "plugins")]
pub mod switch;
#[cfg(feature = "plugins")]
pub mod system_resolver;
#[cfg(feature = "plugins")]
pub mod tls;
#[cfg(feature = "plugins")]
pub mod trojan;
pub mod vmess;
#[cfg(feature = "plugins")]
pub mod ws;

#[cfg(feature = "plugins")]
mod h2;
